#!/sbin/sh

cat /dev/input/event1 > /dev/keycheck&
sleep 3
kill -9 $!
if [ -s /dev/keycheck ]
then
# remount rootfs rw
mount -o remount,rw rootfs /
#mount -t yaffs2 /dev/block/mtdblock2 /cache
#sleep 1
#sync
umount -l /system
umount -l /data

/sbin/recovery &
/sbin/adbd recovery 
fi

#continue booting

