#!/sbin/sh

cat /dev/input/event1 > /dev/keycheck&
sleep 3
kill -9 $!
if [ -s /dev/keycheck -o -e /cache/recovery/boot ]
then
# fixing CPU clocks to avoid issues in recovery
echo 1113600 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo 134400 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq

rm /cache/recovery/boot
mount -o remount,rw rootfs /
umount -l /system
umount -l /data
umount -l /cache
umount -l /mnt/sdcard
rm -r /sdcard
rm -r /not/sdcard
mkdir /sdcard
mkdir /tmp
rm /etc
mkdir /etc
cp /recovery.fstab /etc/recovery.fstab
mount /dev/block/mmcblk0p1 /sdcard
/sbin/recovery &
/sbin/adbd recovery 
fi

/system/bin/chargemon

#continue booting

