TARGET_BOOTLOADER_BOARD_NAME := mogami
TARGET_SPECIFIC_HEADER_PATH := device/semc/anzu/include

TARGET_USES_2G_VM_SPLIT := true

TARGET_BOARD_PLATFORM := msm7x30
TARGET_BOARD_PLATFORM_GPU := qcom-adreno200

TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
ARCH_ARM_HAVE_TLS_REGISTER := true

BOARD_USES_GENERIC_AUDIO := false
TARGET_PROVIDES_LIBAUDIO := true
#TARGET_PROVIDES_LIBRIL := true

BOARD_WPA_SUPPLICANT_DRIVER := CUSTOM
BOARD_WLAN_DEVICE := wl1271
BOARD_SOFTAP_DEVICE := wl1271
WPA_SUPPLICANT_VERSION := VER_0_6_X
WIFI_DRIVER_MODULE_PATH := /system/lib/modules/tiwlan_drv.ko
WIFI_DRIVER_MODULE_NAME := tiwlan_drv
WIFI_FIRMWARE_LOADER := wlan_loader

BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_FM_RADIO := true
BOARD_GLOBAL_CFLAGS += -DHAVE_FM_RADIO

BOARD_USES_QCOM_HARDWARE := true
BOARD_USES_QCOM_LIBS := true
BOARD_USES_QCOM_LIBRPC := true
#BOARD_USES_QCOM_GPS := true
BOARD_USE_QCOM_PMEM := true

BOARD_VENDOR_QCOM_AMSS_VERSION := 50000
BOARD_VENDOR_QCOM_GPS_LOC_API_HARDWARE := semc
BOARD_VENDOR_QCOM_GPS_LOC_API_AMSS_VERSION := 50000

BOARD_EGL_CFG := device/semc/anzu/prebuilt/egl.cfg
BOARD_USE_FRAMEBUFFER_ALPHA_CHANNEL := true
HDMI_DUAL_DISPLAY := true

BOARD_USE_SCREENCAP := true
BOARD_OVERLAY_FORMAT_YCbCr_420_SP := true
BOARD_OVERLAY_MINIFICATION_LIMIT := 2
BOARD_NO_RGBX_8888 := true

TARGET_NO_BOOTLOADER := true
BOARD_HAS_NO_MISC_PARTITION := true
BOARD_USES_RECOVERY_CHARGEMODE := false
BOARD_HAS_NO_SELECT_BUTTON := true

BOARD_KERNEL_CMDLINE := console=null
BOARD_KERNEL_BASE := 0x00200000

BOARD_SDCARD_INTERNAL_DEVICE := /dev/block/mmcblk0p1

#BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00380000
#BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x13880000
#BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x00a00000
BOARD_HAS_NO_SELECT_BUTTON := true
